webproject/webapp/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'table'

urlpatterns = [
    # =====================================================================================>
    # ============================= HOME ==================================================>
    # =====================================================================================>
    path('', views.home, name='home'),
    # =====================================================================================>
    # ============================= Entry Form ============================================>
    # =====================================================================================>
    path('display/', views.displayfunction, name='displayfunction'),
    path('entry_form/', views.entry_form, name='entry_form'),
    # =====================================================================================>
    # ============================= Present Admin =========================================>
    # =====================================================================================>
    path('signin/', views.signin, name='signin'),
    path('log_in/', views.log_in, name='log_in'),
    path('log_out/', views.log_out, name='log_out'),
    path('register/', views.register, name='register'),
    path('registration/', views.registration, name='registration'),
    path('collapsefunction/', views.collapsefunction, name='collapsefunction'),
    path('table/', views.table, name='table'),
    path('table_edit/', views.table_edit, name='table_edit'),
    path('edit_value/', views.edit_value, name='edit_value'),
    path('pdf/', views.pdf, name='pdf'),
    path('csv_file/', views.csv_file, name='csv_file'),
    # =====================================================================================>
    # ============================= Ex. Admin =============================================>
    # =====================================================================================>
    path('exadmin_signin/', views.exadmin_signin, name='exadmin_signin'),
    path('exadmin_login/', views.exadmin_login, name='exadmin_login'),
    path('exadmin_logout/', views.exadmin_logout, name='exadmin_logout'),
    path('exadmin_display/', views.exadmin_display, name='exadmin_display'),
    path('exadmin_table/', views.exadmin_table, name='exadmin_table'),
    # =====================================================================================>
    # ============================= Recycle Bin ===========================================>
    # =====================================================================================>
    path('recycle_signin/', views.recycle_signin, name='recycle_signin'),
    path('recycle_login/', views.recycle_login, name='recycle_login'),
    path('recycle_logout/', views.recycle_logout, name='recycle_logout'),
    path('recycle/', views.recycle, name='recycle'),
    path('recycle_bin/', views.recycle_bin, name='recycle_bin'),
    path('recycle_data/', views.recycle_data, name='recycle_data'),
    path('recycle_pdf/', views.recycle_pdf, name='recycle_pdf'),
    path('recycle_csv/', views.recycle_csv, name='recycle_csv'),


]

webproject/webproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('members/', include('django.contrib.auth.urls')),
]

webproject/webapp/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    service_name = models.CharField(max_length=255)
    service_type = models.CharField(max_length=255)
    active_date = models.CharField(max_length=255)
    renewal_date = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    days = models.CharField(max_length=255)
    # status = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.id} - {self.name} - {self.service_type} - {self.service_name} - {self.active_date} - {self.renewal_date} - {self.owner} - {self.email} - {self.contact} - {self.days}"


class Account(models.Model):
    email = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    password = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.email} - {self.name} - {self.contact} - {self.password}"


class DeletedUsers(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    service_name = models.CharField(max_length=255)
    service_type = models.CharField(max_length=255)
    active_date = models.CharField(max_length=255)
    renewal_date = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    days = models.CharField(max_length=255)
    status = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.id} - {self.name} - {self.service_type} - {self.service_name} - {self.active_date} - {self.renewal_date} - {self.owner} - {self.email} - {self.contact} - {self.days} - {self.status}"

webproject/webapp/views.py
from datetime import datetime
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
# from django.contrib.auth import logout
from django.http import HttpResponse
# from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import *
import re

import csv

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

from xhtml2pdf import pisa
from django.template.loader import get_template
# from .utils import extract_request_variables


# ==============================================================================================================>
# =============================================== Homepage =====================================================>
# ==============================================================================================================>
def home(request): # ========== Homepage Display =========
    return render(request, 'webapp/home.html')


# ==============================================================================================================>
# ===============================================  Entry Form ==================================================>
# ==============================================================================================================>
def displayfunction(request):  # == Entry Form Display ===
    return render(request, 'webapp/form.html')


def entry_form(request):  # ================= Entry Form ==============
    name = request.POST.get('name')
    service_type = request.POST.get('service_type')
    service_name = request.POST.get('service_name')
    active_date = request.POST.get('active_date')
    renewal_date = request.POST.get('renewal_date')
    owner = request.POST.get('owner')
    email = request.POST.get('email')
    contact = request.POST.get('contact')
    days = request.POST.get('days')
    # status = request.POST.get('status')

    if not name:
        context = {'valid': "false"}
        return render(request, 'webapp/form.html', context)
    if not service_name:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if not service_type:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if not active_date:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if not renewal_date:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if not owner:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if not email:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if not contact:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if not days:
        context = {'valid': 'false'}
        return render(request, 'webapp/form.html', context)
    if renewal_date < active_date:
        context = {'valid': 'small'}
        return render(request, 'webapp/form.html', context)

    # For duplicate Service Name ======================================>
    user = User.objects.all()
    for x in user:
        if x.service_name == service_name:
            context = {'valid': 'service_name'}
            return render(request, 'webapp/form.html', context)
    # For contact validation ==============================================>
    pattern = re.compile("(0|01)?[0-9]{11}")
    if not (pattern.match(contact)):
        context = {'valid': 'contact'}
        return render(request, 'webapp/form.html', context)
    # For email validation ============================================>
    pattern = re.compile(r"^[\w\.\+\-]+\@[\w]+\.[a-z]{2,3}$")
    if not (pattern.match(email)):
        context = {'valid': 'email'}
        return render(request, 'webapp/form.html', context)

    # Code for checking Duplicate Date ================================>
    user = User.objects.all()
    for x in user:
        if service_type == x.service_type:
            if x.active_date <= active_date <= x.renewal_date:
                context = {'valid': 'using'}
                return render(request, 'webapp/form.html', context)
            elif x.active_date <= renewal_date <= x.renewal_date:
                context = {'valid': 'using'}
                return render(request, 'webapp/form.html', context)
            if active_date <= x.active_date:
                if renewal_date >= x.active_date:
                    context = {'valid': 'using'}
                    return render(request, 'webapp/form.html', context)

    context = {'valid': 'true'}
    # Create a new User entry in the database using the User model
    user = User(name=name, service_type=service_type, service_name=service_name, active_date=active_date,
                renewal_date=renewal_date, owner=owner, email=email, contact=contact, days=days)
    user.save()
    return render(request, 'webapp/form.html', context)


# ==============================================================================================================>
# ==================================== Present Admin ===========================================================>
# ==============================================================================================================>

# ======= Present Admin Log-in, Log-out Part ========================================>
def signin(request):  # === Present Admin Signin-Display ===
    return render(request, 'webapp/login.html')


def log_in(request):  # ========= Present Admin Login =============
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        if not email:
            return render(request, 'webapp/error.html')
        if not password:
            return render(request, 'webapp/error.html')

        # For email validation =====================================>
        pattern = re.compile(r"^[\w\.\+\-]+\@[\w]+\.[a-z]{2,3}$")
        if not (pattern.match(email)):
            return render(request, 'webapp/error.html')

        # db duplicate checking ====================================>
        account = Account.objects.all()
        for x in account:
            if email == x.email and password == x.password:
                check_user = authenticate(request, username=x.name, password=password)
                if check_user:
                    login(request, check_user)
                    userlist = User.objects.all()
                    context = {'userlist': userlist}
                    return render(request, 'webapp/collapse.html', context)
                else:
                    return HttpResponse("User doesn't exist in Django admin. Please request your admin to register your mail address...")
            else:
                HttpResponse("Wrong Username or Password")
    else:
        return render(request, 'webapp/login.html')


def log_out(request):  # ====== Present Admin Logout ======
    logout(request)
    return render(request, 'webapp/login.html')


# ========== Present Admin Registration Part ==================================>
def register(request):  # ====== Present Admin Registration display ==========
    return render(request, 'webapp/register.html')


def registration(request):  # ======== Present Admin Registration ============
    if request.method == 'POST':
        name = request.POST.get('username')
        email = request.POST.get('email')
        contact = request.POST.get('contact')
        password = request.POST.get('password')
        repeat_password = request.POST.get('repeat_password')
        if password != repeat_password or len(password) < 6:
            return render(request, 'webapp/pass_verification.html')
        # For empty check =========================================>
        if not name:
            return render(request, 'webapp/error.html')
        if not email:
            return render(request, 'webapp/error.html')
        if not contact:
            return render(request, 'webapp/error.html')
        if not password:
            return render(request, 'webapp/error.html')

        # For contact validation ===================================>
        pattern = re.compile("(0|01)?[0-9]{11}")
        if not (pattern.match(contact)):
            return render(request, 'webapp/error.html')
        # For email validation =====================================>
        pattern = re.compile(r"^[\w\.\+\-]+\@[\w]+\.[a-z]{2,3}$")
        if not (pattern.match(email)):
            return render(request, 'webapp/error.html')

        # db duplicate checking ====================================>
        account = Account.objects.all()
        for x in account:
            if email == x.email:
                return render(request, 'webapp/email_error.html')
        # End of db duplicate checking ======================================>

        # Create Edited User entry in the database using the User model
        account = Account(email=email, name=name, contact=contact, password=password)
        account.save()

        return HttpResponse("Registration Successful!")
    else:
        return HttpResponse("Invalid request method.")


@login_required(login_url='/signin/')
def collapsefunction(request):  # ============= Table View =============
    all_user = User.objects.all()
    context = {'userlist': all_user}
    return render(request, 'webapp/collapse.html', context)


# ====== For Table Edit & Delete ======================================================>
@login_required(login_url='/signin/')
def table(request):  # ======== Table value Search and Display =====================
        date_arr = []

webproject/webapp/templates/webapp/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ERROR</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.4/components/error-404s/error-404-1/assets/css/error-404-1.css">
</head>
<body>
<!-- Error 404 Template 1 - Bootstrap Brain Component -->
<section class="py-3 py-md-5 min-vh-100 d-flex justify-content-center align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="text-center">
          <h2 class="d-flex justify-content-center align-items-center gap-2 mb-4">
            <span class="display-1 fw-bold">0</span>
            <i class="bi bi-exclamation-circle-fill text-danger display-4"></i>
            <span class="display-1 fw-bold bsb-flip-h">0</span>
          </h2>
          <h3 class="h2 mb-2">Oops! Input fields can't be EMPTY or Invalid.</h3>
          <p class="mb-5">You have inserted Invalid values. Please Try again...</p>
          <a class="btn bsb-btn-5xl btn-dark rounded-pill px-5 fs-6 m-0" href="http://127.0.0.1:8000/display/" role="button">Back to FORM</a>
        </div>
      </div>
    </div>
  </div>
</section>
</body>
</html>

webproject/webapp/templates/webapp/exadmin_nav.html
<!-- =================================== Nav ================================== -->
<section class="pt-2">
  <form method="post" action="{% url 'table:exadmin_table' %}">
    {% csrf_token %}
  <!-- ============================= Service Type Dropdown ==================================== -->
  <input class="form-control text-center bg-info" type="text" value="Service Type" style="width:100%; color:white;" readonly />
  <div data-mdb-input-init class="form-outline pt-2">
    <select class="form-select shadow" name="service_type" id="service_type" style="width:100%;">
      <option>Domain</option>
      <option>Hosting</option>
      <option>License</option>
      <option>AMC</option>
      <option>Others</option>
      <option>All</option>
    </select>
  </div>
  <!-- ============================= Service Type Dropdown ==================================== -->
  <!-- ============================= DATE ==================================== -->
  <div id="date" class="pt-4">
    <div class="pb-2">
      <input class="form-control text-center bg-info" type="text" value="Service Type" style="width:100%; color:white;" readonly />
    </div>
    <section class="card shadow">
      <div class="card-body bg-light">
        <!-- ======================= JS for checkbox =========================================== -->
        <script>
          function domain_After_disableFunction() {
            // =========== For AFTER ============================>
            if (document.getElementById('domain_After').checked == true) {
              document.getElementById('domain_Before').disabled = true
              document.getElementById('domain_Between').disabled = true
              document.getElementById('domain_renewal_date').disabled = true
              document.getElementById('domain_btn').value = 'AFTER'
            } else if (document.getElementById('domain_After').checked == false) {
              document.getElementById('domain_Before').disabled = false
              document.getElementById('domain_Between').disabled = false
              document.getElementById('domain_renewal_date').disabled = false
            }
          }
          function domain_Before_disableFunction() {
            // =========== For BEFORE ============================>
            if (document.getElementById('domain_Before').checked == true) {
              document.getElementById('domain_After').disabled = true
              document.getElementById('domain_Between').disabled = true
              document.getElementById('domain_renewal_date').disabled = true
              document.getElementById('domain_btn').value = 'BEFORE'
            } else if (document.getElementById('domain_Before').checked == false) {
              document.getElementById('domain_After').disabled = false
              document.getElementById('domain_Between').disabled = false
              document.getElementById('domain_renewal_date').disabled = false
            }
          }
          function domain_Between_disableFunction() {
            // =========== For Between ============================>
            if (document.getElementById('domain_Between').checked == true) {
              document.getElementById('domain_Before').disabled = true
              document.getElementById('domain_After').disabled = true
              document.getElementById('domain_btn').value = 'BETWEEN'
            } else if (document.getElementById('domain_Between').checked == false) {
              document.getElementById('domain_Before').disabled = false
              document.getElementById('domain_After').disabled = false
            }
          }
        </script>
        <!-- ===================================== END JS ============================================ -->
        <div class="form-check">
          <input onclick="domain_After_disableFunction()" class="form-check-input" value="true" type="checkbox" id="domain_After" name="domain_After" />
          <label class="form-check-label" for="domain_After">After</label>
        </div>
        <div class="form-check">
          <input onclick="domain_Before_disableFunction()" class="form-check-input" type="checkbox" value="" id="domain_Before" name="domain_Before"/>
          <label class="form-check-label" for="domain_Before">Before</label>
        </div>
        <div class="form-check">
          <input onclick="domain_Between_disableFunction()" class="form-check-input" type="checkbox" value="" id="domain_Between" name="domain_Between"/>
          <label class="form-check-label" for="domain_Between">Between</label>
        </div>
      </div>
      <!-- ===================== Hidden INPUT =================== -->
      <input type="hidden" id="domain_btn" name="domain_btn" value="false" />
      <!-- ===================== Hidden INPUT =================== -->
      <label class="ps-3 pt-3">From:</label>
      <div class="md-form md-outline input-with-post-icon datepicker ps-3 pe-3">
        <input type="date" name="domain_active" id="domain_active_date" class="form-control" />
      </div>
      <label class="ps-3 pt-3">To:</label>
      <div class="md-form md-outline input-with-post-icon datepicker ps-3 pe-3">
        <input type="date" name="domain_renewal" id="domain_renewal_date" class="form-control" />
      </div>
      <div class="text-center p-2 pt-3">
        <button onclick="return display();" type="submit" style="width:100%;" data-mdb-button-init data-mdb-ripple-init class="btn btn-success" id="submit" name="table_submit">Submit</button>
      </div>
      <script>
        // get the value from the cookie
        var form_date = getCookie("domain_active_date");
        // check a value has been stored
        if (form_date !== '') {
            // if it has update the "p" tag
            document.getElementById("domain_active_date").value = form_date;
        }

        var to_date = getCookie("domain_renewal_date");
        if (to_date !== '') {
            // if it has update the "p" tag
            document.getElementById("domain_renewal_date").value = to_date;
        }

        var btn = getCookie("domain_btn");
        if (btn !== '') {
          document.getElementById("domain_btn").value = btn;
          if (btn == "AFTER") {
            document.getElementById("domain_After").checked = true;
          }
          else if (btn == "BEFORE") {
            document.getElementById("domain_Before").checked = true;
          }
          else if (btn == "BETWEEN") {
            document.getElementById("domain_Between").checked = true;
          }
        }

        var type = getCookie("service_type");
        if (type !== '') {
            // if it has update the "p" tag
            document.getElementById("service_type").value = type;
        }


        function display() {
            var form_date = document.getElementById("domain_active_date").value;
            document.getElementById("domain_active_date").value = form_date;
            var to_date = document.getElementById("domain_renewal_date").value;
            document.getElementById("domain_renewal_date").value = to_date;
            var btn = document.getElementById("domain_btn").value;
            document.getElementById("domain_btn").value = btn;
            var type = document.getElementById("service_type").value;
            document.getElementById("service_type").value = type;

            // store the input in a cookie
            setCookie("domain_active_date", form_date, 1);
            setCookie("domain_renewal_date", to_date, 1);
            setCookie("domain_btn", btn, 1);
            setCookie("service_type", type, 1);


            // if you don't want the page to refresh after the button is pressed then
            // have this function return false.  Also make sure you have "return" in
            // the onclick attribute of the button
            //return false;
        }

        function setCookie(cname, cvalue, exdays) {
          var d = new Date();
          d.setTime(d.getTime() + (exdays*24*60*60*1000));
          var expires = "expires="+ d.toUTCString();
          document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
        }

        function getCookie(cname) {
          var name = cname + "=";
          var decodedCookie = decodeURIComponent(document.cookie);
          var ca = decodedCookie.split(';');
          for(var i = 0; i <ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
              c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
              return c.substring(name.length, c.length);
            }
          }
          return "";
        }

    </script>
    </section>
  </div>
  <div class="pt-3">
  <button onclick="clear_cookies()" type="button" id="clear_all" class="btn btn-dark" style="width:100%">Clear</button>
    <script type="text/javascript">
        function clear_cookies() {
            // Array of specific cookie names to delete
            var cookieNames = ["domain_active_date", "domain_renewal_date", "domain_btn", "domain_After", "domain_Before", "domain_Between"];

            // Loop through each cookie name
            cookieNames.forEach(function(cookieName) {
                // Set the cookie expiration date to a past time (Thu, 01 Jan 1970 00:00:00 GMT)
                document.cookie = cookieName + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/";
            });
            document.getElementById("domain_active_date").value = "";
            document.getElementById("domain_renewal_date").value = "";
            document.getElementById("domain_btn").value = "All";
            document.getElementById("domain_After").checked = "";
            document.getElementById("domain_Before").checked = "";
            document.getElementById("domain_Between").checked = "";
        }
    </script>
    </div>
  </form>
    <div class="pt-2">
      <form method="post" action="{% url 'table:pdf' %}" target="_blank">
        {% csrf_token %}
        <input type="hidden" id="pdf_service" name="service">
        <input type="hidden" id="pdf_active_date" name="active_date">
        <input type="hidden" id="pdf_renewal_date" name="renewal_date">
        <input type="hidden" id="pdf_btn" name="btn">
        <button onclick="pdf()" type="submit" class="btn btn-success btn-sm fw-bold" style="width:100%" name="pdf_button" id="pdf_button" value="true">
          Download PDF<i class="fa-solid fa-file-pdf ps-2"></i>
        </button>
          <script>
          function pdf() {
            document.getElementById("pdf_service").value = document.getElementById("service_type").value;
            document.getElementById("pdf_active_date").value = document.getElementById("domain_active_date").value;
            document.getElementById("pdf_renewal_date").value = document.getElementById("domain_renewal_date").value;
            document.getElementById("pdf_btn").value = document.getElementById("domain_btn").value;
          }
        </script>
      </form>
    </div>
  <div class="pt-2">
    <form method="post" action="{% url 'table:csv_file' %}">
      {% csrf_token %}
      <input type="hidden" id="service" name="service">
      <input type="hidden" id="active_date" name="active_date">
      <input type="hidden" id="renewal_date" name="renewal_date">
      <input type="hidden" id="btn" name="btn">
      <button onclick="csv()" type="submit" class="btn btn-success btn-sm fw-bold" style="width:100%" name="csv_button" id="csv_button" value="true">Download CSV<i class="fa-solid fa-file-csv ps-2"></i></button>
      <script>
        function csv() {
          document.getElementById("service").value = document.getElementById("service_type").value
          document.getElementById("active_date").value = document.getElementById("domain_active_date").value
          document.getElementById("renewal_date").value = document.getElementById("domain_renewal_date").value
          document.getElementById("btn").value = document.getElementById("domain_btn").value
        }
      </script>
    </form>
  </div>
</section>

<!-- =================================== END Nav ================================== -->

webproject/webapp/templates/webapp/login.html
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- - logo -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/b5c2cc2edf.js" crossorigin="anonymous"></script>
  </head>
  <body>
  <!--======== HOME NAV ===========-->
  {% include 'webapp/home_nav.html' %}
  <!--======== HOME NAV End =======-->
    <section>
      <div class="card rounded">
        <div class="row">
          <div class="col-md-7">
            <img src="https://cdn.pixabay.com/photo/2018/01/30/22/50/forest-3119826_1280.jpg" style="width:100%; height:100vh" />
          </div>
          <div class="col-md-5">
            <div class="row d-flex align-items-center justify-content-center h-100">
              <div class="pe-5">
              <form method="post" action="{% url 'table:log_in' %}">
                {% csrf_token %}
                  <!-- Email input -->
                  <div data-mdb-input-init class="form-outline mb-4 ps-3 pt-2">
                    <label class="form-label fw-bold lead" for="email"><i class="fa-solid fa-envelope pe-3"></i>Email Address</label>
                    <input type="email" placeholder="Email Address" id="email" name="email" class="form-control form-control-lg shadow" />
                  </div>

                  <!-- Password input -->
                  <div data-mdb-input-init class="form-outline mb-4 ps-3">
                    <label class="form-label fw-bold lead" for="password"><i class="fa-solid fa-key pe-3"></i>Password</label>
                    <input type="password" placeholder="Password" id="password" name="password" class="form-control form-control-lg shadow" />
                  </div>

                  <div class="d-flex justify-content-center align-items-center mb-4">
                    <a href="http://127.0.0.1:8000/register/">Create Account?</a>
                  </div>
                  <div class="ps-3">
                    <!-- Submit button -->
                    <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg btn-block col-4"><i class="fa-solid fa-right-to-bracket pe-3"></i>Sign in</button>
                  </div>
              </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>